overrides:
  ceph:
    conf:
      osd:
        osd op queue: debug_random
        osd op queue cut off: debug_random
        osd debug verify missing on start: true
        osd debug verify cached snaps: true
        osd debug inject dispatch delay duration: 0.4
        osd debug inject dispatch delay probability: 0.3
      mon:
        mon scrub interval: 300
